name: Build & publish PyPI packages

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.**

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build sdist package
        run: |
          python -m pip install pip build --upgrade
          python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: "dist/*.tar.gz"

  build-win64-wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheel for py${{ matrix.python-version }}
        run: |
          python -m pip install pip build --upgrade
          python -m build --wheel
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: "dist/*.whl"

  pypi-publish:
    # if: github.event_name == 'release' && github.event.action == 'published'
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build-sdist, build-win64-wheels]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: packages
        path: dist
    - name: List produced packages
      run: |
        du -bh dist/*
    - name: Test PyPI publish
      if: false
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip_existing: true
    - name: PyPI publish
      if: false
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
